server:
  port: 8084

spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      group-id: Group1
      auto-offset-reset: earliest
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

# Swagger/OpenAPI Configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    doc-expansion: none     # Optional: controls UI expansion
    filter: true           # Optional: enables search filter
  api-docs:
    path: /api-docs     # JSON endpoint
  default-consumes-media-type: application/json  # Optional
  default-produces-media-type: application/json